#!/bin/bash

cd /home/manish/Desktop/machine/omnibioai_workbench/work/demo_wdl/cromwell-executions/hello_wdl/5241a9d1-f9ef-4aa3-b254-f11a8790d77a/call-hello/execution
tmpDir=$(mktemp -d "$PWD"/tmp.XXXXXX)

export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"


(
cd /home/manish/Desktop/machine/omnibioai_workbench/work/demo_wdl/cromwell-executions/hello_wdl/5241a9d1-f9ef-4aa3-b254-f11a8790d77a/call-hello/execution

)


out5241a9d1="${tmpDir}/out.$$" err5241a9d1="${tmpDir}/err.$$"
mkfifo "$out5241a9d1" "$err5241a9d1"
trap 'rm "$out5241a9d1" "$err5241a9d1"' EXIT
touch '/home/manish/Desktop/machine/omnibioai_workbench/work/demo_wdl/cromwell-executions/hello_wdl/5241a9d1-f9ef-4aa3-b254-f11a8790d77a/call-hello/execution/stdout' '/home/manish/Desktop/machine/omnibioai_workbench/work/demo_wdl/cromwell-executions/hello_wdl/5241a9d1-f9ef-4aa3-b254-f11a8790d77a/call-hello/execution/stderr'
tee '/home/manish/Desktop/machine/omnibioai_workbench/work/demo_wdl/cromwell-executions/hello_wdl/5241a9d1-f9ef-4aa3-b254-f11a8790d77a/call-hello/execution/stdout' < "$out5241a9d1" &
tee '/home/manish/Desktop/machine/omnibioai_workbench/work/demo_wdl/cromwell-executions/hello_wdl/5241a9d1-f9ef-4aa3-b254-f11a8790d77a/call-hello/execution/stderr' < "$err5241a9d1" >&2 &
(
cd /home/manish/Desktop/machine/omnibioai_workbench/work/demo_wdl/cromwell-executions/hello_wdl/5241a9d1-f9ef-4aa3-b254-f11a8790d77a/call-hello/execution


echo "Hello from OmnibioAI WDL workflow"
)  > "$out5241a9d1" 2> "$err5241a9d1"
echo $? > /home/manish/Desktop/machine/omnibioai_workbench/work/demo_wdl/cromwell-executions/hello_wdl/5241a9d1-f9ef-4aa3-b254-f11a8790d77a/call-hello/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /home/manish/Desktop/machine/omnibioai_workbench/work/demo_wdl/cromwell-executions/hello_wdl/5241a9d1-f9ef-4aa3-b254-f11a8790d77a/call-hello/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /home/manish/Desktop/machine/omnibioai_workbench/work/demo_wdl/cromwell-executions/hello_wdl/5241a9d1-f9ef-4aa3-b254-f11a8790d77a/call-hello/execution
sync


)
mv /home/manish/Desktop/machine/omnibioai_workbench/work/demo_wdl/cromwell-executions/hello_wdl/5241a9d1-f9ef-4aa3-b254-f11a8790d77a/call-hello/execution/rc.tmp /home/manish/Desktop/machine/omnibioai_workbench/work/demo_wdl/cromwell-executions/hello_wdl/5241a9d1-f9ef-4aa3-b254-f11a8790d77a/call-hello/execution/rc

