#!/bin/bash

cd /home/manish/Desktop/machine/omnibioai_workbench/work/demo_wdl/cromwell-executions/hello_wdl/4baf51c7-5363-46b1-8ff5-869a22c90008/call-hello/execution
tmpDir=$(mktemp -d "$PWD"/tmp.XXXXXX)

export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"


(
cd /home/manish/Desktop/machine/omnibioai_workbench/work/demo_wdl/cromwell-executions/hello_wdl/4baf51c7-5363-46b1-8ff5-869a22c90008/call-hello/execution

)


out4baf51c7="${tmpDir}/out.$$" err4baf51c7="${tmpDir}/err.$$"
mkfifo "$out4baf51c7" "$err4baf51c7"
trap 'rm "$out4baf51c7" "$err4baf51c7"' EXIT
touch '/home/manish/Desktop/machine/omnibioai_workbench/work/demo_wdl/cromwell-executions/hello_wdl/4baf51c7-5363-46b1-8ff5-869a22c90008/call-hello/execution/stdout' '/home/manish/Desktop/machine/omnibioai_workbench/work/demo_wdl/cromwell-executions/hello_wdl/4baf51c7-5363-46b1-8ff5-869a22c90008/call-hello/execution/stderr'
tee '/home/manish/Desktop/machine/omnibioai_workbench/work/demo_wdl/cromwell-executions/hello_wdl/4baf51c7-5363-46b1-8ff5-869a22c90008/call-hello/execution/stdout' < "$out4baf51c7" &
tee '/home/manish/Desktop/machine/omnibioai_workbench/work/demo_wdl/cromwell-executions/hello_wdl/4baf51c7-5363-46b1-8ff5-869a22c90008/call-hello/execution/stderr' < "$err4baf51c7" >&2 &
(
cd /home/manish/Desktop/machine/omnibioai_workbench/work/demo_wdl/cromwell-executions/hello_wdl/4baf51c7-5363-46b1-8ff5-869a22c90008/call-hello/execution


echo "Hello from OmnibioAI WDL workflow"
)  > "$out4baf51c7" 2> "$err4baf51c7"
echo $? > /home/manish/Desktop/machine/omnibioai_workbench/work/demo_wdl/cromwell-executions/hello_wdl/4baf51c7-5363-46b1-8ff5-869a22c90008/call-hello/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /home/manish/Desktop/machine/omnibioai_workbench/work/demo_wdl/cromwell-executions/hello_wdl/4baf51c7-5363-46b1-8ff5-869a22c90008/call-hello/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /home/manish/Desktop/machine/omnibioai_workbench/work/demo_wdl/cromwell-executions/hello_wdl/4baf51c7-5363-46b1-8ff5-869a22c90008/call-hello/execution
sync


)
mv /home/manish/Desktop/machine/omnibioai_workbench/work/demo_wdl/cromwell-executions/hello_wdl/4baf51c7-5363-46b1-8ff5-869a22c90008/call-hello/execution/rc.tmp /home/manish/Desktop/machine/omnibioai_workbench/work/demo_wdl/cromwell-executions/hello_wdl/4baf51c7-5363-46b1-8ff5-869a22c90008/call-hello/execution/rc

