# Generated by Django 5.2.1 on 2025-05-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pipeline_type",
                    models.CharField(
                        choices=[
                            ("rnaseq", "RNA-seq"),
                            ("wgs", "Whole Genome Sequencing"),
                            ("wes", "Whole Exome Sequencing"),
                            ("methylation", "Methylation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("input_file", models.FileField(upload_to="input_files/")),
                ("out_dir", models.TextField(blank=True, null=True)),
                ("status", models.CharField(default="PENDING", max_length=50)),
                ("log", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
