# Generated by Django 5.2.1 on 2025-05-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline_manager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="reference_genome",
            field=models.CharField(default="hg38", max_length=100),
        ),
    ]
