# Generated by Django 5.2.1 on 2025-05-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline_manager", "0002_job_reference_genome"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="input_file",
            new_name="input_file_r1",
        ),
        migrations.AddField(
            model_name="job",
            name="input_file_r2",
            field=models.FileField(blank=True, null=True, upload_to="input_files/"),
        ),
    ]
